const ScheduleActionTypes = {
    SET_SCHEDULES: 'SET_SCHEDULES',
    SELECT_SCHEDULES: 'SELECT_SCHEDULES',
    EXTRACT_SCHEDULES: 'EXTRACT_SCHEDULES',
    RESET_SCHEDULES: 'RESET_SCHEDULES',
    ADD_SCHEDULE: 'ADD_SCHEDULE',
    UPDATE_SCHEDULES: 'UPDATE_SCHEDULES',
    DELETE_SCHEDULE: 'DELETE_SCHEDULE',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default ScheduleActionTypes;