const CommonDifficultyActionTypes = {
    SET_COMMON_DIFFICULTIES: 'SET_COMMON_DIFFICULTIES',
    ADD_COMMON_DIFFICULTY: 'ADD_COMMON_DIFFICULTY',
    UPDATE_COMMON_DIFFICULTIES: 'UPDATE_COMMON_DIFFICULTIES',
    DELETE_COMMON_DIFFICULTY: 'DELETE_COMMON_DIFFICULTY',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default CommonDifficultyActionTypes;