const EmployeeActionTypes = {
    SET_EMPLOYEE_MAP: 'SET_EMPLOYEE_MAP',
    SET_EMPLOYEES: 'SET_EMPLOYEES',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    SIGNOUT_USER: 'SIGNOUT_USER'
}

export default EmployeeActionTypes;