const StepActionTypes = {
    SET_SINGLE_STEP: 'SET_SINGLE_STEP',
    SET_STEPS: 'SET_STEPS',
    ADD_STEP: 'ADD_STEP',
    UPDATE_STEPS: 'UPDATE_STEPS',
    DELETE_STEP: 'DELETE_STEP',
    SET_SINGLE_OBJECTIVE: 'SET_SINGLE_OBJECTIVE',
    SET_ALL_OBJECTIVES: 'SET_ALL_OBJECTIVES',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default StepActionTypes;