const DepartmentActionTypes = {
    SET_DEPARTMENTS: 'SET_ALL_DEPARTMENTS',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default DepartmentActionTypes;