const ObjectiveActionTypes = {
    SET_SINGLE_OBJECTIVE: 'SET_SINGLE_OBJECTIVE',
    SET_OBJECTIVES: 'SET_ALL_OBJECTIVES',
    ADD_OBJECTIVE: 'ADD_OBJECTIVE',
    UPDATE_OBJECTIVES: 'UPDATE_OBJECTIVES',
    UPDATE_SINGLE_OBJECTIVE: 'UPDATE_SINGLE_OBJECTIVE',
    DELETE_OBJECTIVE: 'DELETE_OBJECTIVE',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default ObjectiveActionTypes;